version: '3'

services:
  app:
    image: dannalopez/as222s5_t09_be:latest
    ports:
      - "8085:8085"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      API_KEY: ${API_KEY}
