name: Docker Build and Push

on:
  push:
    branches:
      - develop

jobs:
  docker-build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
